# Start the development server
run-server:
	poetry run python manage.py runserver

# Create a superuser
create-superuser:
	poetry run python manage.py createsuperuser

# Apply migrations
migrate:
	poetry run python manage.py migrate

# Create new migrations (optional: APP=app_name)
makemigrations:
	poetry run python manage.py makemigrations $(APP)
