# Generated by Django 5.2.6 on 2025-10-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_seed_emotions'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='student.student'),
        ),
    ]
